-- urban_cavemining items for es_extended (run once on your database)
INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
    ('pickaxe', 'Pickaxe', 3, 0, 1),
    ('miningdrill', 'Mining Drill', 4, 0, 1),
    ('drillbit', 'Drill Bit', 1, 0, 1),
    ('mininglaser', 'Mining Laser', 5, 0, 1),
    ('goldpan', 'Gold Pan', 1, 0, 1),
    ('mining_helmet', 'Mining Helmet', 1, 0, 1),
    ('stone', 'Stone', 1, 0, 1),
    ('coal', 'Coal', 1, 0, 1),
    ('copperore', 'Copper Ore', 1, 0, 1),
    ('ironore', 'Iron Ore', 1, 0, 1),
    ('tinore', 'Tin Ore', 1, 0, 1),
    ('leadore', 'Lead Ore', 1, 0, 1),
    ('bauxite', 'Bauxite', 1, 0, 1),
    ('goldore', 'Gold Ore', 1, 0, 1),
    ('goldnugget', 'Gold Nugget', 1, 0, 1),
    ('uncut_ruby', 'Uncut Ruby', 1, 0, 1),
    ('uncut_emerald', 'Uncut Emerald', 1, 0, 1),
    ('uncut_sapphire', 'Uncut Sapphire', 1, 0, 1),
    ('uncut_diamond', 'Uncut Diamond', 1, 0, 1),
    ('copper', 'Copper Ingot', 1, 0, 1),
    ('iron', 'Iron Ingot', 1, 0, 1),
    ('tin', 'Tin Ingot', 1, 0, 1),
    ('lead', 'Lead Ingot', 1, 0, 1),
    ('aluminum', 'Aluminium Ingot', 1, 0, 1),
    ('steel', 'Steel Ingot', 1, 0, 1),
    ('bronze', 'Bronze Ingot', 1, 0, 1),
    ('goldingot', 'Gold Ingot', 1, 0, 1),
    ('ruby', 'Ruby', 1, 0, 1),
    ('emerald', 'Emerald', 1, 0, 1),
    ('sapphire', 'Sapphire', 1, 0, 1),
    ('diamond', 'Diamond', 1, 0, 1),
    ('gold_ring', 'Gold Ring', 1, 0, 1),
    ('goldchain', 'Gold Chain', 1, 0, 1),
    ('ruby_ring', 'Ruby Ring', 1, 0, 1),
    ('emerald_ring', 'Emerald Ring', 1, 0, 1),
    ('sapphire_ring', 'Sapphire Ring', 1, 0, 1),
    ('diamond_ring', 'Diamond Ring', 1, 0, 1),
    ('ruby_necklace', 'Ruby Necklace', 1, 0, 1),
    ('emerald_necklace', 'Emerald Necklace', 1, 0, 1),
    ('sapphire_necklace', 'Sapphire Necklace', 1, 0, 1),
    ('diamond_necklace', 'Diamond Necklace', 1, 0, 1),
    ('ruby_earring', 'Ruby Earrings', 1, 0, 1),
    ('emerald_earring', 'Emerald Earrings', 1, 0, 1),
    ('sapphire_earring', 'Sapphire Earrings', 1, 0, 1),
    ('diamond_earring', 'Diamond Earrings', 1, 0, 1);
